name: Secure Scan

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "21 4 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  secureci:
    uses: TIDHQ-NETWORK/TID-SecureCI/.github/workflows/tid-secureci.yml@daa9d4eb971ee2c117f7f77edb0f7bab050b6870
    secrets: inherit
    with:
      enforce: true
      fail_severity: HIGH,CRITICAL
